config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users
  resources :posts
  resources :faqs
  resources :categories
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources "greeting" do 
    collection do
      get "say_goodmorning"
      get "say_goodafternoon"
    end
  end
  resources :random_image
  resources :contact

  root "projects#index"
  # create route /project/:project_id/tickets/:id
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end

  resources :attachments, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :faqs
  validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :author, class_name: "User", optional: true

  validates :text, presence: true
  delegate :project, to: :ticket

  scope :persisted, lambda { where.not(id: nil) }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :firstname, :surname, :email
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :question
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :project

  def self.available_roles
    %w{manager editor viewer}
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User", optional: true
  validates :name, :description, presence: true
  validates :description, length: { minimum: 10 }
  mount_uploader :attachment, AttachmentUploader
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :excluding_archived, lambda { where(archived_at: nil) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
    @categories = Category.all
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
    @categories = Category.all
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Learning Rails").join(" - ")
      end
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(faq) do |f| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area :answer %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <select name="faq[category_id]">
      <% @categories.each do |category| %>
        <option value="<%= category.id %>"
      <%= ' selected' if category.id == @faq.category_id %>>
      <%= category.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faqs</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= faq.category_id %></td>
        <td><%= link_to 'Show', faq %></td>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<p>
  <strong>Category:</strong>
  <%= @faq.category_id %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>