config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users
  resources :posts
  resources :faqs
  resources :categories
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources "greeting" do 
    collection do
      get "say_goodmorning"
      get "say_goodafternoon"
    end
  end
  resources :random_image
  resources :contact

  root "projects#index"
  # create route /project/:project_id/tickets/:id
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end

  resources :attachments, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :faqs
  validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :author, class_name: "User", optional: true

  validates :text, presence: true
  delegate :project, to: :ticket

  scope :persisted, lambda { where.not(id: nil) }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :firstname, :surname, :email
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :question
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :project

  def self.available_roles
    %w{manager editor viewer}
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User", optional: true
  validates :name, :description, presence: true
  validates :description, length: { minimum: 10 }
  mount_uploader :attachment, AttachmentUploader
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :excluding_archived, lambda { where(archived_at: nil) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def new
    @project = Project.new
    @categories = Category.all
  end

  # POST request
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project has been created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project has been deleted.' }
    end
  end

  private 

  def project_params
    params.require(:project).permit(:name, :description, :category_id)
  end

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = policy_scope(Project)
  end

  def show 
    authorize @project, :show?
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project has been updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description, :category_id)
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Learning Rails").join(" - ")
      end
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, project], html: { class: 'form-block' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/admin/projects/new.html.erb
<div class=page-header">
  <h1>New Project</h1>
</div>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/_form.html.erb
<%= simple_form_for(project, html: { class: 'form-block' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<header>
  <h1>Editing Project</h1>
</header>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<header>
  <h1>Projects</h1>
  <% admins_only do %>
    <ul class="actions">
      <li>
        <%= link_to "New Project", new_admin_project_path, class: "new" %>
      </li>
    </ul>
  <% end %>
</header>

<div id="projects">
  <% @projects.each do |project| %>
    <h2><%= link_to project.name, project %></h2>
    <p><%= project.description %></p>
  <% end %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<header>
  <h1><%= @project.name %></h1>

  <ul class="actions">
    <% if policy(@project).update? %>
      <li>
        <%= link_to "Edit Project", edit_project_path(@project), class: "edit" %>
      </li>
    <% end %>
    <% admins_only do %>
      <li>
        <%= link_to "Delete Project", admin_project_path(@project), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: "delete" %>
      </li>
    <% end %>
  </ul>
</header>

<%= title(@project.name, "Projects") %>
<%= link_to 'Back', projects_path %>

<header>
  <h2>Tickets</h2>

  <ul class="actions">
    <% if policy(Ticket.new(project: @project)).create? %>
      <li><%= link_to "New Ticket", new_project_ticket_path(@project), class: "new" %></li>
    <% end %>
  </ul>
</header>

<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.name, [@project, ticket] %>
    </li>
  <% end %>
</ul>